name: 'Prepare theKey Project for run'
description: 'The Key Prepare scripts'
inputs:
  decrypt_key:
    description: 'Decrypt Key'
    required: true
    default: ''
runs:
  using: "composite"
  steps:
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Decrypt files
      uses: klee0kai/screwdriver@dev
      with:
        cmd: "decrypt_file --key ${{ inputs.decrypt_key }} --in_file ./apkSert.jks.encrypted --out_file ./apkSert.jks"
    - uses: klee0kai/screwdriver@dev
      with:
        cmd: "decrypt_file --key ${{ inputs.decrypt_key }} --in_file ./keystore.properties.encrypted --out_file ./keystore.properties"

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      shell: bash

    - name: Grant execute permission for env_build
      run: chmod +x env_build.sh
      shell: bash

