name: 'Prepare theKey Project for run'
description: 'The Key Prepare scripts'
runs:
  using: "composite"
  steps:
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Installs
      run: sudo apt-get install libprotobuf-dev protobuf-compiler
      shell: bash

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      shell: bash

    - name: Grant execute permission for env_build
      run: chmod +x env_build.sh
      shell: bash

