name: Deploy Release

on:
  workflow_dispatch:
  push:
    branches:
      - 'release/**'
      - 'releases/**'

jobs:
  gh_release_diff:
    name: Collect Changes with Master
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - uses: klee0kai/screwdriver@dev
        with:
          gh_api_token: ${{ secrets.SECRETS_GH_API_TOKEN }}
          cmd: "gh_release_diff  -l -d --summary -w changes.md"

      - name: Upload changes artifacts
        uses: actions/upload-artifact@v3
        with:
          name: changes
          path: |
            ./changes.md


  build_and_artifact:
    name: Build and Artifact
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
      - name: Decrypt files
        uses: klee0kai/screwdriver@dev
        with:
          cmd: "decrypt --key ${{ secrets.ENCRYPT_KEY }} --file_name ./apkSert.jks.ecrypted -w ./apkSert.jks"
      - uses: klee0kai/screwdriver@dev
        with:
          cmd: "decrypt --key ${{ secrets.ENCRYPT_KEY }} --file_name ./keystore.properties.ecrypted -w ./keystore.properties"

      - name: Prepare build env
        run: source env_build.sh
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Release
        run: build_term_app

      - name: Build Release
        run: build_apk

      - name: Upload changes artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: |
            ./builds
