name: Deploy Prebuild

on:
  workflow_dispatch:

jobs:
  prebuild_openssl:
    name: Build OpenSSL lib
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - uses: actions/checkout@v4
      - name: Prepare Env
        uses: ./.github/actions/prepare
        with:
          decrypt_key: ${{ secrets.ENCRYPT_KEY }}

      - name: Download OpenSSL
        run: ./env_build.sh download_openssl
      - name: Build OpenSSL for curOS
        run: ./env_build.sh build_openssl_cur_os
      - name: Build OpenSSL for Android
        run: ./env_build.sh build_openssl_android_all

      - name: Upload OpenSSL libs
        uses: actions/upload-artifact@v3
        with:
          name: openssl
          path: |
            ./third_party_libraries/build
