name: Deploy Release

on:
  workflow_dispatch:
  push:
    branches:
      - 'release/**'
      - 'releases/**'

jobs:
  gh_release_diff:
    name: Collect Changes with Master
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
      - uses: klee0kai/screwdriver@dev
        with:
          gh_api_token: ${{ secrets.SECRETS_GH_API_TOKEN }}
          cmd: "gh_release_diff  -l -d --summary -w changes.md"

      - name: Upload changes artifacts
        uses: actions/upload-artifact@v3
        with:
          name: changes
          path: |
            ./changes.md

  build_community_and_artifact:
    name: Build Community apk
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - uses: actions/checkout@v4
      - name: Prepare Env
        uses: ./.github/actions/prepare

      - name: Build Term Release
        run: ./env_build.sh build_term_app

      - name: Build Community Apk Release
        run: ./gradlew assembleRelease

      - name: Upload changes artifacts
        uses: actions/upload-artifact@v3
        with:
          name: community_builds
          path: |
            ./builds
            ./*/build/outputs

  build_commercial_and_artifact:
    name: Build Commercial apk
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.SECRETS_GH_API_TOKEN }}

      - name: Prepare Env
        uses: ./.github/actions/prepare

      - name: Build Term Release
        run: ./env_build.sh build_term_app

      - name: Build Commercial Apk Release
        run: ./gradlew assembleCommercialRelease

      - name: Upload changes artifacts
        uses: actions/upload-artifact@v3
        with:
          name: commercial_builds
          path: |
            ./builds
            ./*/build/outputs
