name: Deploy Dev Branch

on:
  workflow_dispatch:
  push:
    branches:
      - 'release/**'
      - 'releases/**'
      - 'master'
      - 'dev'

jobs:
  term_tests:
    name: Run Term Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/prepare
        with:
          decrypt_key: ${{ secrets.ENCRYPT_KEY }}

      - name: Build and test
        run: ./env_build.sh build_term_app

  app_tests:
    name: Run App Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/prepare
        with:
          decrypt_key: ${{ secrets.ENCRYPT_KEY }}

      - name: Test with Gradle
        continue-on-error: true
        run: ./gradlew test
      - name: Upload test artifacts
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: |
            ./**/build/reports
            ./**/build/test-results

  mikepenz_report:
    name: Prepare Mikepenz Test Report
    needs: app_tests
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - uses: actions/checkout@v3
      - name: Download Test Artifact
        uses: actions/download-artifact@v3
        with:
          name: test-report

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        with:
          report_paths: '**/build/test-results/**/*.xml'
          detailed_summary: true
          check_name: Mikepenz JUnit Test Report



      
