name: Deploy Dev Branch

on:
  workflow_dispatch:
  push:
    branches:
      - 'release/**'
      - 'releases/**'
      - 'master'
      - 'dev'

jobs:
  lint_code:
    name: Build Android App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/prepare

      - name: Lint Code
        run: ./gradlew lint

  term_tests:
    name: Run Term Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/prepare

      - name: Build and test
        run: ./env_build.sh build_term_app

  app_build:
    name: Assemble build all code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/prepare

      - name: Gradle assemble
        run: ./gradlew assemble

  app_unit_tests:
    name: Run App Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/prepare
      - name: Test with Gradle
        run: ./gradlew testDebugUnitTest
      - name: Upload test artifacts
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: |
            ./**/build/reports
            ./**/build/test-results

  app_paparazzi:
    name: Collect app preview Images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/prepare
      - name: Test with Gradle
        run: ./gradlew recordPaparazziDebug
      - name: Upload test artifacts
        uses: actions/upload-artifact@v3
        with:
          name: screenshots
          path: |
            ./**/src/test/snapshots/images/**

  mikepenz_report:
    name: Prepare Mikepenz Test Report
    if: ${{ always() }}
    needs: app_unit_tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download Test Artifact
        uses: actions/download-artifact@v3
        with:
          name: test-report

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        with:
          report_paths: '**/build/test-results/**/*.xml'
          detailed_summary: true
          check_name: Mikepenz JUnit Test Report



      
